import PushNotification from 'react-native-push-notification'

export const localNotification = (soundName) => {
   PushNotification.localNotification({
      channelId: soundName ? 'sound-channel-id' : 'default-channel-id',
      ticker: 'My Notification Ticker',
      autoCancel: true,
      largeIcon: 'ic_stat_unnamed',
      smallIcon: 'ic_stat_unnamed',
      bigText: 'My big text that will be shown when notification is expanded',
      subText: 'This is a subText',
      color: 'yellow',
      vibrate: true,
      vibration: 300,
      tag: 'some_tag',
      group: 'group',
      groupSummary: false,
      ongoing: false,
      actions: ['Yes', 'No'],
      invokeApp: true,
      when: null,
      usesChronometer: false,
      timeoutAfter: null,
      category: '',
      subtitle: "My Notification Subtitle",
      id: lastId,
      title: 'Local Notification',
      message: 'My Notification Message',
      userInfo: { screen: 'Home' },
      playSound: !!soundName,
      soundName: soundName ? soundName : 'default',
      number: 10,
   })
}

export const scheduledLocalNotification = (soundName) => {
   PushNotification.localNotificationSchedule({
      date: new Date(Date.now() + 10 * 1000),
      channelId: soundName ? 'sound-channel-id' : 'default-channel-id',
      ticker: 'My Notification Ticker',
      autoCancel: true,
      largeIcon: 'ic_stat_unnamed',
      smallIcon: 'ic_stat_unnamed',
      bigText: 'My big text that will be shown when notification is expanded',
      subText: 'This is a subText',
      color: 'blue',
      vibrate: true,
      vibration: 300,
      tag: 'some_tag',
      group: 'group',
      groupSummary: false,
      ongoing: false,
      actions: ['Yes', 'No'],
      invokeApp: false,
      when: null,
      usesChronometer: false,
      timeoutAfter: null,
      category: '',
      id: lastId,
      title: 'Scheduled Notification',
      message: 'My Notification Message',
      userInfo: { screen: "Home" },
      playSound: !!soundName,
      soundName: soundName ? soundName : 'default',
      number: 10,
   })
}
